root: true

extends:
  - "@vue/eslint-config-typescript"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "prettier"

parserOptions:
  project: tsconfig.json
  extraFileExtensions:
    - .vue

overrides:
  - files: ["*.{js,ts}"]
  - files: ["src/**/*.{js,ts,vue}"]
    env:
      browser: true
  - files: ["**/*.vue"]
    extends:
      - "plugin:vue/recommended"
      - "plugin:prettier-vue/recommended"
